[project]
name = "graphneuralnetworkdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
	"Flask>=2.0",
	"networkx>=3.0",
	"numpy>=1.26"
]
